# sudo requirement
sudo: required

# repo language
language: python

# language version
python:
  - '3.6'

# external service
services:
  - mysql

# specific mysql version
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

# configure environment
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS coin_arrival'

# dependency installation
install:
  pip install -r requirements.txt

# configure environment
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sudo service mysql restart

# test script
script:
  - cd BackEnd
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py test

# toggle branch
branches:
  only:
   - master

# notification settings
notifications:
  email:
    recipients:
      - xuwy27@mail2.sysu.edu.cn
    on_success: never # default: change
    on_failure: always # default: always