version: '3'
services:
  coin_arrival_db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=coin_arrival
      - MYSQL_ROOT_PASSWORD=root

  backend:
    build: .
    command: bash ./start.sh
    volumes:
      - .:/home/coinArrival/BackEnd
    ports:
      - "8000:8000"
    links:
      - coin_arrival_db