# Generated by Django 2.1.4 on 2019-06-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_info', '0003_auto_20190625_2234'),
        ('task_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField()),
                ('answer', models.CharField(max_length=300, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_info.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User')),
            ],
        ),
    ]
