# Generated by Django 2.1.4 on 2019-06-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_info', '0003_auto_20190625_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('types', models.CharField(max_length=50)),
                ('reward', models.FloatField()),
                ('deadline', models.CharField(max_length=50)),
                ('repeatTime', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User')),
            ],
        ),
    ]
