# Generated by Django 2.1.4 on 2019-06-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField()),
                ('answer', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('types', models.CharField(max_length=50)),
                ('reward', models.FloatField()),
                ('deadline', models.CharField(max_length=50)),
                ('repeatTime', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('major', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=30, null=True)),
                ('studentID', models.CharField(max_length=30, null=True)),
                ('teacherID', models.CharField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User'),
        ),
        migrations.AddField(
            model_name='accepttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.Task'),
        ),
        migrations.AddField(
            model_name='accepttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User'),
        ),
    ]
