# Generated by Django 2.1.4 on 2019-06-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptTask',
            fields=[
                ('acceptTaskID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('isFinished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('taskName', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('type', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('isCompleted', models.BooleanField()),
                ('repeatTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.BooleanField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('school', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('studentID', models.CharField(max_length=30)),
                ('teacherID', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User')),
            ],
        ),
        migrations.DeleteModel(
            name='account_info',
        ),
        migrations.AddField(
            model_name='task',
            name='issuerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User'),
        ),
        migrations.AddField(
            model_name='accepttask',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.Task'),
        ),
        migrations.AddField(
            model_name='accepttask',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_info.User'),
        ),
    ]
