# Generated by Django 2.1.4 on 2019-06-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
