# Generated by Django 2.1.4 on 2019-06-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0002_auto_20190625_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='accepttask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='issuer',
        ),
        migrations.DeleteModel(
            name='AcceptTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
