# Generated by Django 2.1.4 on 2019-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0002_auto_20190622_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.FloatField(),
        ),
    ]
