# Generated by Django 2.1.4 on 2019-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_info', '0003_auto_20190622_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepttask',
            name='answer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
